#!/usr/bin/env ruby

require 'cleanfb'

class String
  def magenta;  "\e[35m#{self}\e[0m" end
end

cleaner = Cleanfb::Clean.new
cleaner.parse_input

unless ARGV.include? "restore"
  response = cleaner.remove
else
  response = cleaner.restore
end

unless response.nil? || response.empty? || (response.include? "Please")
  puts response.magenta
else
  puts response
end
