#!/usr/bin/env ruby

require 'cleanfb'

class String
	def magenta;	"\e[35m#{self}\e[0m" end
end

cleaner = Cleanfb::Clean.new

unless ARGV.include? "restore"
	response = cleaner.remove
else
	respone = cleaner.restore
end

unless response.nil? || response.empty? || (response.include? "Please")
	puts response.magenta
else
	puts response
end
